In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\OneDrive\Documents\Downloads\Hospital_Project\patients_raw.csv")

In [3]:
df.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02
3,4,P00004,Patient_WYKTO,25.0,Male,NaN,Heart Failure,Self Pay,Middle,2017-03-23
4,5,P00005,Patient_PFFLA,54.0,Male,NaN,Asthma,Basic Insurance,Middle,2021-11-22

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12090 entries, 0 to 12089
Data columns (total 10 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   patient_id                 12090 non-null  int64
 1   patient_code               12090 non-null  object
 2   patient_name               12090 non-null  object
 3   age                        11879 non-null  float64
 4   gender                     12090 non-null  object
 5   city                       11920 non-null  object
 6   primary_chronic_condition  8841 non-null   object
 7   insurance_plan             12090 non-null  object
 8   income_segment             12090 non-null  object
 9   registration_date          12090 non-null  object
dtypes: float64(1), int64(1), object(8)
memory usage: 944.7+ KB

In [5]:
df.isnull().sum()

patient_id                      0
patient_code                    0
patient_name                    0
age                           211
gender                          0
city                          170
primary_chronic_condition    3249
insurance_plan                  0
income_segment                  0
registration_date               0
dtype: int64

In [6]:
text_cols = [
    "patient_code",
    "patient_name",
    "gender",
    "city",
    "primary_chronic_condition",
    "insurance_plan",
    "income_segment"
]

for col in text_cols:
    df[col] = df[col].str.strip()

In [7]:
len(df)

12090

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df = df.drop_duplicates()

In [10]:
df.dtypes

patient_id                     int64
patient_code                  object
patient_name                  object
age                          float64
gender                        object
city                          object
primary_chronic_condition     object
insurance_plan                object
income_segment                object
registration_date             object
dtype: object

In [11]:
df["registration_date"] = pd.to_datetime(
    df["registration_date"],
    format="mixed",
    dayfirst=True
)

In [12]:
df["age"] = df["age"].fillna(
    df["age"].median()
)

In [13]:
df["age"] = df["age"].astype(int)

In [14]:
df.dtypes

patient_id                            int64
patient_code                         object
patient_name                         object
age                                   int64
gender                               object
city                                 object
primary_chronic_condition            object
insurance_plan                       object
income_segment                       object
registration_date            datetime64[ns]
dtype: object

In [15]:
df["city"] = df["city"].fillna("Unknown")

In [16]:
df["primary_chronic_condition"] = (
    df["primary_chronic_condition"]
    .fillna("Unknown")
)

In [17]:
df["gender"] = df["gender"].str.title()

In [18]:
df["insurance_plan"] = (
    df["insurance_plan"].str.title()
)

In [19]:
df["income_segment"] = (
    df["income_segment"].str.title()
)

In [20]:
df["gender"].unique()

array(['Female', 'Male', 'Other', 'M', 'Unknown', 'F', 'Femle'],
      dtype=object)

In [21]:
df["income_segment"].unique()

array(['Low', 'Middle', 'Upper Middle', 'High'], dtype=object)

In [22]:
df["gender"] = df["gender"].replace({
    "M": "Male",
    "F": "Female",
    "Femle": "Female"
})

In [23]:
df["gender"].unique()

array(['Female', 'Male', 'Other', 'Unknown'], dtype=object)

In [24]:
df[df["age"] < 0]

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
963,964,P00964,Patient_LUPLE,-3,Male,Delhi,Unknown,Self Pay,Low,2018-02-10
1929,1930,P01930,Patient_ELBHO,-3,Female,Kolkata,Unknown,Self Pay,Middle,2017-09-14
2980,2981,P02981,Patient_FYOXO,-3,Female,Kolkata,Unknown,Government Scheme,Low,2018-12-11
3806,3807,P03807,Patient_QUZIA,-3,Female,Pune,Diabetes,Basic Insurance,Upper Middle,2013-10-15
4924,4925,P04925,Patient_IVRQK,-3,Female,Kolkata,CKD,Government Scheme,Middle,2020-06-30
5540,5541,P05541,Patient_ANSKW,-3,Male,Kolkata,Diabetes,Self Pay,Low,2013-01-17
5827,5828,P05828,Patient_FTETR,-3,Male,Kolkata,Hypertension,Self Pay,Low,2024-03-27
5896,5897,P05897,Patient_KPVTV,-3,Male,Jaipur,Asthma,Corporate Insurance,Upper Middle,2016-11-29
6042,6043,P06043,Patient_WKCFC,-3,Female,Chennai,Diabetes,Corporate Insurance,Middle,2018-05-27
6695,6696,P06696,Patient_WMUDD,-3,Female,Pune,Diabetes,Basic Insurance,Middle,2018-10-10
11589,11590,P11590,Patient_QTDBQ,-3,Female,Vijayawada,Diabetes,Government Scheme,Middle,2014-02-07

In [25]:
df[df["age"] > 120]

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
437,438,P00438,Patient_FVNKQ,150,Male,Pune,Hypertension,Self Pay,Low,2022-12-27
612,613,P00613,Patient_LOQMR,135,Male,Chennai,Heart Failure,Basic Insurance,Middle,2023-09-30
1493,1494,P01494,Patient_QYTGA,150,Female,Delhi,Diabetes,Premium Insurance,Upper Middle,2015-02-02
2226,2227,P02227,Patient_UMOQT,150,Male,Mumbai,Asthma,Premium Insurance,Middle,2021-11-11
2705,2706,P02706,Patient_XOSAU,150,Female,Warangal,Asthma,Government Scheme,Low,2017-09-17
2796,2797,P02797,Patient_XCYPC,135,Female,Bengaluru,Diabetes,Government Scheme,Middle,2024-01-06
3269,3270,P03270,Patient_DKKYY,150,Female,Hyderabad,Unknown,Government Scheme,Middle,2021-01-16
3334,3335,P03335,Patient_WCPPL,150,Other,Chennai,Unknown,Corporate Insurance,Middle,2014-08-11
3453,3454,P03454,Patient_JEMAD,135,Male,Kolkata,CKD,Basic Insurance,Middle,2022-09-29
3943,3944,P03944,Patient_NOOSF,150,Female,Ahmedabad,Unknown,Self Pay,Low,2018-08-20
3969,3970,P03970,Patient_JQBIS,135,Male,Mumbai,Diabetes,Government Scheme,Low,2013-09-09
4097,4098,P04098,Patient_TBUTR,135,Male,Delhi,COPD,Basic Insurance,Low,2015-02-14
4158,4159,P04159,Patient_VKBKL,135,Male,Ahmedabad,Diabetes,Government Scheme,Middle,2016-06-18
5236,5237,P05237,Patient_AMHGX,135,Female,Kolkata,Hypertension,Self Pay,Low,2022-05-09
5547,5548,P05548,Patient_ABJHM,150,Female,Ahmedabad,Unknown,Self Pay,Middle,2021-10-14
5909,5910,P05910,Patient_TINHY,150,Female,Mumbai,Hypertension,Premium Insurance,Low,2023-12-17
6379,6380,P06380,Patient_MNGHY,135,Female,Vijayawada,Unknown,Corporate Insurance,Middle,2018-12-02
6395,6396,P06396,Patient_XUMAV,150,Female,Jaipur,Unknown,Premium Insurance,Upper Middle,2015-10-05
6411,6412,P06412,Patient_YTQWE,150,Female,Ahmedabad,CKD,Corporate Insurance,Upper Middle,2014-09-30
7039,7040,P07040,Patient_PJUZI,150,Male,Hyderabad,Diabetes,Premium Insurance,Low,2010-04-03
7079,7080,P07080,Patient_KUHZL,150,Male,Jaipur,Asthma,Government Scheme,Upper Middle,2020-02-21
7155,7156,P07156,Patient_RADHW,150,Female,Kolkata,Diabetes,Corporate Insurance,Middle,2020-11-02
7466,7467,P07467,Patient_BNYPJ,150,Male,Kolkata,CKD,Government Scheme,Low,2015-10-25
7528,7529,P07529,Patient_GJQND,135,Male,Chennai,Unknown,Self Pay,Low,2021-06-20
7692,7693,P07693,Patient_CQBNX,150,Male,Bengaluru,Diabetes,Basic Insurance,Middle,2016-10-28
8026,8027,P08027,Patient_QCSVA,135,Female,Kolkata,Hypertension,Government Scheme,Low,2016-07-08
8450,8451,P08451,Patient_TFFBP,150,Female,Bengaluru,Hypertension,Basic Insurance,Upper Middle,2014-12-09
8796,8797,P08797,Patient_UKQHJ,150,Male,Bengaluru,CKD,Basic Insurance,Middle,2010-10-06
8993,8994,P08994,Patient_UVPWR,150,Male,Nagpur,Asthma,Corporate Insurance,Middle,2012-12-02
10175,10176,P10176,Patient_VVOUV,150,Male,Bengaluru,Unknown,Self Pay,Low,2011-11-21
10177,10178,P10178,Patient_GFLAE,150,Male,Nagpur,COPD,Basic Insurance,Upper Middle,2012-06-20
10437,10438,P10438,Patient_QEOWU,135,Female,Kolkata,Diabetes,Government Scheme,Middle,2017-03-14
10685,10686,P10686,Patient_QAFGW,135,Male,Indore,Unknown,Self Pay,Low,2018-04-19

In [26]:
df["age"] = pd.to_numeric(
    df["age"],
    errors="coerce"
)

In [27]:
df.loc[
    (df["age"] <= 0) | (df["age"] >= 110),
    "age"
] = np.nan

In [28]:
df.head()

,patient_id,patient_code,patient_name,age,gender,city,primary_chronic_condition,insurance_plan,income_segment,registration_date
0,1,P00001,Patient_BKOKF,46.0,Female,Hyderabad,Heart Failure,Premium Insurance,Low,2016-09-25
1,2,P00002,Patient_KXPSW,58.0,Male,Hyderabad,Heart Failure,Basic Insurance,Low,2022-09-12
2,3,P00003,Patient_TJAJT,51.0,Female,Ahmedabad,Hypertension,Government Scheme,Middle,2014-08-02
3,4,P00004,Patient_WYKTO,25.0,Male,Unknown,Heart Failure,Self Pay,Middle,2017-03-23
4,5,P00005,Patient_PFFLA,54.0,Male,Unknown,Asthma,Basic Insurance,Middle,2021-11-22

In [29]:
df.to_csv("cleaned_patients.csv", index=False)