In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("D:\OneDrive\Documents\Downloads\Hospital_Project\pharmacy_orders_raw.csv")

In [3]:
df.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
0,1,29377,7899,Insulin,15,57.66,864.90,IP Pharmacy
1,2,25956,2404,Anticoagulant,1,33.52,33.52,IP Pharmacy
2,3,18883,6450,Chemotherapy Drug,17,188.65,3207.07,OP Pharmacy
3,4,21967,10792,Metformin,3,37.73,113.18,OP Pharmacy
4,5,17705,4645,Amlodipine,20,95.68,1913.64,OP Pharmacy

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 70090 entries, 0 to 70089
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       70090 non-null  int64
 1   admission_id   70090 non-null  int64
 2   patient_id     70090 non-null  int64
 3   medicine_name  70090 non-null  object
 4   quantity       70090 non-null  int64
 5   unit_price     70090 non-null  float64
 6   line_amount    69940 non-null  float64
 7   pharmacy_type  70090 non-null  object
dtypes: float64(2), int64(4), object(2)
memory usage: 4.3+ MB

In [5]:
df.isnull().sum()

order_id           0
admission_id       0
patient_id         0
medicine_name      0
quantity           0
unit_price         0
line_amount      150
pharmacy_type      0
dtype: int64

In [6]:
text_cols = [
    "medicine_name",
    "pharmacy_type"
]

for col in text_cols:
    df[col] = df[col].str.strip()

In [7]:
len(df)

70090

In [8]:
df.duplicated().sum()

np.int64(90)

In [9]:
df = df.drop_duplicates()

In [10]:
len(df)

70000

In [11]:
df.dtypes

order_id           int64
admission_id       int64
patient_id         int64
medicine_name     object
quantity           int64
unit_price       float64
line_amount      float64
pharmacy_type     object
dtype: object

In [12]:
df["quantity"] = df["quantity"].fillna(
    df["quantity"].median()
)

In [13]:
df["quantity"] = df["quantity"].astype(int)

In [14]:
df["unit_price"] = df["unit_price"].fillna(
    df["unit_price"].median()
)

In [15]:
df["line_amount"] = df["line_amount"].fillna(
    df["line_amount"].median()
)

In [16]:
df.loc[
    df["quantity"] <= 0,
    "quantity"
] = np.nan

In [17]:
df.loc[
    df["line_amount"] <= 0,
    "line_amount"
] = np.nan

In [18]:
df.loc[
    df["unit_price"] <= 0,
    "unit_price"
] = np.nan

In [19]:
df["line_amount"] = df["line_amount"].fillna(
    df["line_amount"].median()
)

In [20]:
df["pharmacy_type"] = (
    df["pharmacy_type"]
    .str.strip()
    .str.title()
)

In [21]:
df["pharmacy_type"].unique()

array(['Ip Pharmacy', 'Op Pharmacy'], dtype=object)

In [22]:
df["pharmacy_type"] = df["pharmacy_type"].replace({
    "Ip Pharmacy": "IP Pharmacy",
    "Op Pharmacy": "OP Pharmacy"
})

In [23]:
df[
    round(df["quantity"] * df["unit_price"], 2)
    != round(df["line_amount"], 2)
]

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
2,3,18883,6450,Chemotherapy Drug,17.0,188.65,3207.07,OP Pharmacy
3,4,21967,10792,Metformin,3.0,37.73,113.18,OP Pharmacy
4,5,17705,4645,Amlodipine,20.0,95.68,1913.64,OP Pharmacy
5,6,27131,991324,Salbutamol,17.0,187.50,3187.44,IP Pharmacy
6,7,8004,4886,Amlodipine,7.0,48.63,340.39,IP Pharmacy
...,...,...,...,...,...,...,...,...
69994,69995,19767,4960,Atorvastatin,20.0,41.82,836.39,IP Pharmacy
69995,69996,22220,11775,Metformin,19.0,91.48,1738.19,OP Pharmacy
69996,69997,24282,2610,Salbutamol,16.0,29.48,471.75,OP Pharmacy
69997,69998,15209,1671,Chemotherapy Drug,20.0,56.30,1125.93,IP Pharmacy
69999,70000,13280,10886,Painkiller,5.0,16.89,84.43,IP Pharmacy

In [24]:
df["line_amount"] = (
    df["quantity"] * df["unit_price"]
).round(2)

In [27]:
df.isnull().sum()

order_id         0
admission_id     0
patient_id       0
medicine_name    0
quantity         0
unit_price       0
line_amount      0
pharmacy_type    0
dtype: int64

In [25]:
df.head()

,order_id,admission_id,patient_id,medicine_name,quantity,unit_price,line_amount,pharmacy_type
0,1,29377,7899,Insulin,15.0,57.66,864.90,IP Pharmacy
1,2,25956,2404,Anticoagulant,1.0,33.52,33.52,IP Pharmacy
2,3,18883,6450,Chemotherapy Drug,17.0,188.65,3207.05,OP Pharmacy
3,4,21967,10792,Metformin,3.0,37.73,113.19,OP Pharmacy
4,5,17705,4645,Amlodipine,20.0,95.68,1913.60,OP Pharmacy

In [26]:
df.to_csv(
    "cleaned_pharmacy_orders.csv",
    index=False
)